### ISSUE TITLE
implementation of projection

### ISSUE THREAD

**Issue by arnofoo** [martiansideofthemoon/logic-rules-sentiment#1]
Thanks for your code and your work. I can't find your implementation of projection from your code. I only find a function named "evaluate_projection", but it don't show the process of projecting the trained model into a rule-regularized subspace. Can you help me find out the process of projecting. 
Thank you!

**Comment by martiansideofthemoon** [comment]
Hi, this might be helpful: https://github.com/martiansideofthemoon/logic-rules-sentiment/blob/master/code/train.py#L107-L123. Feel free to re-open the issue if something is still unclear.
